title: Add Playmode tint to show when your project is running
hero_image: images/banner.png
description: Add Playmode tint to show when your project is running
version: 4
listed: false
copyedit: false
last_tested: "2021-11-29"
steps:
  - title: Add Playmode tint to show when your project is running
